# Standard labels for SmartFlowSite
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: chore
  color: cccccc
  description: Maintenance / cleanup
- name: docs
  color: 0075ca
  description: Documentation changes
- name: ci
  color: 0e8a16
  description: CI/CD related
- name: test
  color: 5319e7
  description: Tests or QA
- name: security
  color: ededed
  description: Security-related
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: question
  color: d876e3
  description: Further information is requested
- name: duplicate
  color: cfd3d7
- name: invalid
  color: e4e669
- name: wontfix
  color: ffffff
- name: urgent
  color: ff0000
  description: Needs priority attention
