# Standard labels for SmartFlowSite (keeps your current names)
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: chore
  color: cccccc
  description: Maintenance / cleanup

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: github_actions
  color: 6f42c1
  description: Pull requests that update GitHub Actions code

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on
