#!/usr/bin/env bash
set -euo pipefail

# Change to repo root
for d in "$HOME/workspace/SmartFlowSite" "$HOME/SmartFlowSite" "$PWD"; do
  [ -d "$d/.git" ] && { cd "$d"; break; }
done

# Stage all changes
git add .

# Set commit message and description automatically
COMMIT_MSG="Auto-commit: update at $(date '+%Y-%m-%d %H:%M:%S')"
COMMIT_DESC="This is an automated commit generated by git-auto-commit.sh"

# Commit with message + description
git commit -m "$COMMIT_MSG" -m "$COMMIT_DESC" || echo "Nothing to commit"

# Push to main
git push origin main
