[deployment]
run = "python3 main.py"
ignorePorts = false

[deployment.env]
PORT = "5000"
FLASK_ENV = "production"
FLASK_APP = "server.py"

[run]
command = "python3 main.py"

[nix.channel]
channel = "stable-23.11"