entrypoint = "app.py"

[env]
PYTHONUNBUFFERED = "1"
PORT = "5000"

[interpreter]
type = "python3"

[deployment]
run = [
  "python3","-m","gunicorn","app:app",
  "--bind","0.0.0.0:$PORT","--workers","2","--threads","4","--timeout","120"
]