import express from "express";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express(); const PORT = process.env.PORT || 3000;
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));
app.get("/", (_r, res) => res.redirect("/landing"));
app.get("/health", (_r, res) => res.send("ok"));
app.listen(PORT, () => console.log(`SmartFlow static on :${PORT}`));
