name: DIAGNOSE
description: Swift triage using Runbook-Diagnose.md
title: "DIAGNOSE: <symptom>"
labels: ["diagnose"]
body:
  - type: input
    id: symptom
    attributes: {label: "Symptom", placeholder: "What you see"}
  - type: textarea
    id: steps
    attributes: {label: "Steps to reproduce", placeholder: "Click-by-click"}
  - type: textarea
    id: expected
    attributes: {label: "Expected vs Actual", placeholder: "What should happen vs what did"}
  - type: textarea
    id: logs
    attributes: {label: "Logs/Screens", placeholder: "Paste key lines or attach"}
  - type: dropdown
    id: area
    attributes:
      label: "Area"
      options: ["SmartFlowSite","SocialScaleBooster","SFSDataQueryEngine","SFSAPDemoCRM","CI/CD"]
