name: STATUS package
description: 5-part SmartFlow status reply scaffold
title: "STATUS: <scope>"
labels: ["status"]
body:
  - type: markdown
    attributes:
      value: "Fill the 5 parts. Keep it short."
  - type: textarea
    id: changes
    attributes: {label: "1) Changes in Replit/GitHub", placeholder: "List files or 'none'."}
  - type: textarea
    id: commits
    attributes: {label: "2) Commits / Issues / PRs", placeholder: "IDs or 'none'."}
  - type: textarea
    id: roadmap
    attributes: {label: "3) Roadmap updates", placeholder: "New/shifted items."}
  - type: textarea
    id: next
    attributes: {label: "4) Next 3 small moves", placeholder: "- [ ] one\n- [ ] two\n- [ ] three"}
  - type: textarea
    id: tools
    attributes: {label: "5) Tools / tricks", placeholder: "Short tips or links."}
