name: CI (Reusable SFS)

on:
  push:
    branches: [ "main", "dev", "release/**", "hotfix/**", "sfs-power-**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  use-reusable:
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@fix/ci-reusable-20251004T155604Z
    with:
      service: portalflow
      env: staging
    secrets:
      SFS_PAT: ${{ secrets.SFS_PAT }}
    permissions:
      contents: read
      actions: read
      id-token: write