name: Build static pages
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: "0 8 * * *" # daily at 08:00 UTC to rebuild (in case content was edited online)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run build
      - name: Commit generated files
        run: |
          git config user.name "sfs-bot"
          git config user.email "bot@smartflow.local"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(build): refresh blog/updates/rss/sitemap"
            git push