name: sfs-ci-deploy

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "main"
      - "users/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install backend deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt; skipping."
          fi

  build_pages:
    name: build_pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (if package.json exists)
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm ci
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci
      - name: npm run build
        if: ${{ hashFiles('package.json') != '' && hashFiles('package-lock.json') != '' }}
        run: npm run build
      - name: Skip
        if: ${{ hashFiles('package.json') == '' }}
        run: echo "No package.json; skipping build_pages."

  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List
        run: ls -la

  ci_build:
    name: ci / build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Marker
        run: echo "CI / build OK"

  sfs-diagnose:
    name: sfs-diagnose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Diagnose
        run: |
          du -sh . || true
          git status

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pytest
        if: ${{ hashFiles('tests/**') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q
      - name: No tests present
        if: ${{ hashFiles('tests/**') == '' }}
        run: echo "No tests/; skipping."

  codeql:
    name: CodeQL / Analyze sfs-ci-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python, javascript
      - uses: github/codeql-action/analyze@v3
