name: ci

on:
  push:
    branches:
      - "main"
      - "tune/**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  platform-ci:
    name: Platform CI suite
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@main
    with:
      service: smartflowsite
      env: dev
      python_version: "3.11"
    secrets:
      SFS_PAT: ${{ secrets.SFS_PAT }}

  project-tests:
    name: Project test and lint matrix
    runs-on: ubuntu-latest
    needs: platform-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run JavaScript tests
        run: npm test -- --watch=false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: pytest
