- name: Check SFS secrets
  run: |
    test -n "${{ secrets.SFS_PAT }}"      || (echo SFS_PAT MISSING && exit 1)
    test -n "${{ secrets.REPLIT_TOKEN }}" || (echo REPLIT_TOKEN MISSING && exit 1)
    test -n "${{ secrets.SFS_SYNC_URL }}" || (echo SFS_SYNC_URL MISSING && exit 1)
