name: ci
on:
  push: { branches: ["main","tune/**"] }
  pull_request: { branches: ["main"] }
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  reuse:
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@main
    secrets: inherit
