name: ci

on:
  push:
    branches: [ "main", "tune/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build ok"

  build_pages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build_pages ok"

  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build-test ok"

  sfs-diagnose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sfs-diagnose ok"
