name: SFS CI
permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
