
name: SFS CI + Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  reuse:
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@main
    secrets: inherit
