name: Health check (SmartFlowSite)
on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if URL not set
        run: 'test -n "${{ secrets.SFS_HEALTH_URL_SITE }}"'
      - name: Curl /health with retries
        run: |
          URL="${{ secrets.SFS_HEALTH_URL_SITE }}"
          echo "Pinging: $URL"
          for i in {1..12}; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$URL")
            echo "Attempt $i → $code"
            if [ "$code" = "200" ]; then exit 0; fi
            sleep 5
          done
          echo "Health check failed"; exit 1
