name: Sync Labels
on:
  push:
    branches: [main]
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels-sync.yml"
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
