name: Sync Labels
on:
  push:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels-sync.yml"
  workflow_dispatch:

# Needed to create/update repo labels
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
