name: Markdown Check
on:
  pull_request:
    paths: ["**/*.md","**/*.yml","**/*.yaml"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Checking line endings and trailing spaces…"
          ! grep -RIn $'\t' -- '**/*.md' || (echo "Tabs found in MD files"; exit 1)
          ! grep -RIn ' $' -- '**/*.md' || (echo "Trailing spaces found"; exit 1)
