name: Markdown Check
on:
  pull_request:
    paths: ["**/*.md","**/*.yml","**/*.yaml"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint tracked Markdown/YAML
        shell: bash
        run: |
          set -euo pipefail
          files_md=$(git ls-files '*.md' || true)
          files_yml=$(git ls-files '*.yml' '*.yaml' || true)
          echo "Checking tabs/trailing spaces…"
          [ -z "$files_md$files_yml" ] && exit 0
          if [ -n "$files_md" ]; then
            ! grep -RIn $'\t' -- $files_md || { echo "Tabs found in MD"; exit 1; }
            ! grep -RIn ' $'  -- $files_md || { echo "Trailing spaces in MD"; exit 1; }
          fi
          if [ -n "$files_yml" ]; then
            ! grep -RIn ' $'  -- $files_yml || { echo "Trailing spaces in YAML"; exit 1; }
          fi
