name: Deploy Pages
on: {push: {branches: [main]}}
permissions: {pages: write, id-token: write, contents: read}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: {path: "."}
      - uses: actions/deploy-pages@v4
