name: pip-audit
on:
  pull_request:
    paths:
      - "requirements*.txt"
      - "pyproject.toml"
      - "poetry.lock"
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with: { python-version: "3.x" }
      - run: python -m pip install --upgrade pip pip-audit
      - run: pip-audit -r requirements.txt || (echo "pip-audit found issues"; exit 1)
        if: hashFiles('requirements.txt') != ''
