name: PR Decorate
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  decorate:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Write summary
        run: |
          echo "### SmartFlow CI ✓" >> "$GITHUB_STEP_SUMMARY"
          echo "- Brand: Black/Brown/Gold" >> "$GITHUB_STEP_SUMMARY"
