name: Replit Auto Sync

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Example step (you can add your own commands here)
      - name: Run Replit sync
        run: |
          echo "✅ Repo synced. You can add commands here to auto-deploy or notify Replit."