name: Reusable SFS CI
on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Validate repo (light)
        run: |
          python -V
          echo "OK"
