name: Reusable SFS CI
on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ inputs.python_version }}
      - name: Validate repo (light)
        run: |
          python -V
          echo "OK"
