name: SmartFlow Tools Lint
permissions:
  contents: read

on:
  push:
    paths:
      - "tools/**"
      - ".github/workflows/sf-shellcheck.yml"
  pull_request:
    paths:
      - "tools/**"
      - ".github/workflows/sf-shellcheck.yml"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck || true
      - name: Lint shell scripts in tools/
        run: |
          shopt -s nullglob
          files=(tools/*.sh tools/*.bash tools/*.zsh tools/*/*.sh)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No shell scripts to check."
          else
            shellcheck -S style "${files[@]}"
          fi
