name: SmartFlow Tools Lint
permissions:
  contents: read

on:
  push:
    paths:
      - "tools/**"
      - ".github/workflows/sf-shellcheck.yml"
    paths-ignore:
      - "tools/archive/**"
  pull_request:
    paths:
      - "tools/**"
      - ".github/workflows/sf-shellcheck.yml"
    paths-ignore:
      - "tools/archive/**"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck || true
      - name: Lint shell scripts in tools/
        run: |
          set -euo pipefail
          mapfile -t files < <(find tools -type f \( -name '*.sh' -o -name '*.bash' -o -name '*.zsh' \) ! -path 'tools/archive/*')
          if [ "${#files[@]}" -eq 0 ]; then
            echo "No shell scripts to check."
          else
            shellcheck -S style "${files[@]
