name: SFS Reusable CI Deploy
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: '20'
    secrets:
      SFS_PAT:
        required: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { token: ${{ secrets.SFS_PAT }} }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ inputs.node_version }} }
      - run: npm ci || true
      - run: echo "Reusable CI OK for $GITHUB_REPOSITORY:$GITHUB_REF_NAME"
