name: SFS CI Deploy
on:
  workflow_call:
    inputs:
      service: { type: string, required: false, default: smartflowsite }
      env:     { type: string, required: false, default: dev }
      python_version: { type: string, required: false, default: "3.11" }
    secrets:
      SFS_PAT: { required: false }
jobs:
  reuse:
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@main
