name: SmartFlow Rules CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.x'
      - name: Check SmartFlow rules & PR body
        run: python .github/scripts/sfs-rules-check.py
