name: SFS Reusable CI + Deploy
on:
  workflow_call:
    inputs:
      service: { required: true, type: string }
      env: { required: true, type: string }
    secrets:
      SFS_PAT: { required: true }
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ inputs.service }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo inputs
        run: |
          echo "Service=${{ inputs.service }}  Env=${{ inputs.env }}"
      - name: Guard secret
        if: ${{ !secrets.SFS_PAT }}
        run: echo "Missing SFS_PAT (set at Org Secrets)"; exit 1
