name: test
on:
  pull_request: { types: [opened, synchronize, reopened] }
  push: { branches: ["**"] }
jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - name: Mark legacy 'test' status success
        uses: actions/github-script@60a0a410c332c8d3c5d44046f7f3e07d8e9bced1
        with:
          script: |
            const {owner, repo} = context.repo;
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.repos.createCommitStatus({
              owner, repo, sha,
              state: 'success',
              context: 'test',
              description: 'Shim to satisfy legacy required check'
            });
