name: verify-sfs-pat
on:
  workflow_dispatch:
  push: { paths: [".github/workflows/verify-sfs-pat.yml"] }

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure secret is present
        run: |
          if [ -z "${{ secrets.SFS_PAT }}" ]; then
            echo "❌ Missing Actions secret SFS_PAT"; exit 1; fi
          echo "✅ SFS_PAT is present"

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Authenticate with GitHub API (/user)
        run: |
          set -euo pipefail
          headers="$(mktemp)"; body="$(mktemp)"
          code=$(curl -sS -w '%{http_code}' -o "$body" -D "$headers" \
            -H "Authorization: Bearer ${{ secrets.SFS_PAT }}" \
            -H "Accept: application/vnd.github+json" https://api.github.com/user)
          echo "http_code=$code"
          if [ "$code" != "200" ]; then echo "❌ GitHub auth failed ($code)"; echo "Body:"; cat "$body"; exit 1; fi
          login=$(jq -r '.login // empty' "$body" 2>/dev/null || true)
          [ -n "$login" ] && echo "✅ Auth OK as: $login" || echo "✅ Auth OK (fine-grained token likely)"
          echo "— Key headers —"
          grep -Ei '^(x-oauth-scopes|x-ratelimit|date):' "$headers" | sed 's/\r$//'
          echo "———————"
# touch 20251025T204643Z
